<?php

namespace AppBundle\Repository;

/**
 * CityChoicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityChoicesRepository extends \Doctrine\ORM\EntityRepository
{
}
